[project]
name = "llm4codesec-llm-benchmark"
version = "0.1.0"
description = ""
authors = [{ name = "vodkar", email = "boombarah@gmail.com" }]
requires-python = ">=3.10,<4"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [
    "torch>=2.0.0",
    "torchvision>=0.15.0",
    "torchaudio>=2.0.0",
    "transformers>=4.51.0",
    "tokenizers>=0.14.0",
    "accelerate>=0.24.0",
    "bitsandbytes>=0.41.0",
    "pandas>=2.0.0",
    "numpy>=1.24.0",
    "scikit-learn>=1.3.0",
    "datasets>=2.14.0",
    "tqdm>=4.65.0",
    "psutil>=5.9.0",
    "huggingface-hub[hf_xet]>=0.32.4,<0.33",
    "packaging>=25.0,<26",
    "ninja>=1.11.1.4,<2",
    "fbgemm-gpu>=1.4.1",
    "tiktoken>=0.9.0,<0.10",
    "protobuf>=6.31.1,<7",
    "ipykernel>=6.29.5,<7",
]

[dependency-groups]
dev = ["ruff>=0.11.13,<0.12"]
analytics = [
    "matplotlib>=3.10.3,<4",
    "seaborn>=0.13.2,<0.14",
    "plotly>=6.2.0,<7",
]

[tool.uv]
package = false
default-groups = [
    "dev",
    "analytics",
]

[[tool.uv.index]]
name = "pytorch"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[[tool.uv.index]]
name = "pytorch-nightly"
url = "https://download.pytorch.org/whl/nightly/cu128"
explicit = true

[tool.uv.sources]
torch = { index = "pytorch" }
torchvision = { index = "pytorch" }
torchaudio = { index = "pytorch" }
fbgemm-gpu = { index = "pytorch" }

[build-system]
requires = ["uv_build>=0.9.26,<0.10.0"]
build-backend = "uv_build"
